name: 'Manual Test Execution'

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        required: true
        description: 'Target environment'
        options:
          - test

jobs:
  test:
    name: cypress ubuntu-22.04
    runs-on: ubuntu-22.04
    env:
      CI: true
      TARGET: ${{ github.event.inputs.target }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Cypress run
        uses: cypress-io/github-action@v5.0.9
        with:
          browser: chrome

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results
          retention-days: 20

      - name: Generate allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 100

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          keep_files: true
